version: '3.8'

services:
  web:
    build: .
    ports:
      - "3000:80"
    volumes:
      - .:/usr/share/nginx/html
    container_name: climatrack-web

  jenkins:
    build:
      context: ./jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: climatrack-jenkins

volumes:
  jenkins_home:
